services:
  app-dev: # Сервис разработки user-service
    build:
      context: ../services/user-service
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ../services/user-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users-service
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=user-service
      - KAFKA_GROUP_ID=user-service
    depends_on: # Зависимость от сервиса db
      - db
      - redis
      - kafka
    command: sh -c "npm install && npm run start:dev" # Команда для запуска приложения в режиме разработки

  product-app-dev: # Сервис разработки product-service
    build:
      context: ../services/product-service
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ../services/product-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker # чтобы Nest читал .docker.env
    depends_on:
      - product-db
      - redis
      - kafka
    command: sh -c "npm install && npm run start:dev"

  order-app-dev: # Сервис разработки order-service
    build:
      context: ../services/order-service
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    volumes:
      - ../services/order-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker # чтобы Nest читал .docker.env
    depends_on:
      - order-db
      - redis
      - kafka
    command: sh -c "npm install && npm run start:dev"

  cart-app-dev: # Сервис разработки order-service
    build:
      context: ../services/cart-service
      dockerfile: Dockerfile.dev
    ports:
      - "5003:5003"
    volumes:
      - ../services/cart-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker # чтобы Nest читал .docker.env
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=cart-service
      - KAFKA_GROUP_ID=cart-service
    depends_on:
      - cart-db
      - redis
      - kafka
    command: sh -c "npm install && npm run start:dev"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      # 9092 - для контейнеров внутри docker network (kafka:9092)
      # 9094 - для приложений, запущенных на хост-машине (localhost:9094)
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      # Два listener'а:
      # - PLAINTEXT слушает внутри docker network
      # - PLAINTEXT_HOST нужен для подключений с твоего ПК
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: always

  redis-insight: # не работает через браузер
    image: redis/redisinsight:latest
    ports:
      - "8002:8001"
    volumes:
      - redis-insight-data:/db
    restart: always
    depends_on:
      - redis

  db: # Сервис базы данных для user-service
    container_name: db_user
    image: postgres:14-alpine # Используем образ Postgres
    ports:
      - "5433:5432" # Порт для доступа к базе данных
    environment: # Переменные окружения
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users-service
    volumes:
      - postgres_data:/var/lib/postgresql/data # Волюм для хранения данных базы данных при остановке контейнера
    restart: always

  product-db: # Сервис базы данных для product-service
    container_name: db_product
    image: postgres:14-alpine
    ports:
      - "5434:5432" # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-service
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    restart: always

  order-db: # Сервис базы данных для order-service
    container_name: db_order
    image: postgres:14-alpine
    ports:
      - "5435:5432" # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order-service
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    restart: always
  cart-db: # Сервис базы данных для cart-service
    container_name: db_cart
    image: postgres:14-alpine
    ports:
      - "5436:5432" # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cart-service
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin: # Сервис pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment: # Переменные окружения
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on: # Зависимость от сервиса db
      - db
    restart: always # Перезапуск сервиса при изменении

volumes: # Волюмы для хранения данных баз данных
  postgres_data: # сохраняет данные Postgres для user-service
  product_postgres_data: # сохраняет данные Postgres для product-service
  order_postgres_data: # сохраняет данные Postgres для order-service
  cart_postgres_data: # сохраняет данные Postgres для cart-service
  mongodb_data: # сохраняет данные MongoDB
  redis-data: # сохраняет данные Redis
  redis-insight-data: # сохраняет данные RedisInsight
