services:
  gateway-app-dev: # Сервис разработки gateway-service
    container_name: gateway-app-dev
    build:
      context: ../services/gateway
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ../services/gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker
      - USER_SERVICE_URL=http://app-dev:5000
      - PRODUCT_SERVICE_URL=http://product-app-dev:5001
      - ORDER_SERVICE_URL=http://order-app-dev:5002
      - CART_SERVICE_URL=http://cart-app-dev:5003
    # API Gateway не зависит от баз данных, он перенаправляет запросы на микросервисы
    depends_on:
      - redis # для кэширования
      - kafka # для обмена сообщениями
      - app-dev
      - product-app-dev
      - order-app-dev
      - cart-app-dev
    command: sh -c "npm install && npx cross-env NODE_ENV=docker nest start --watch"
  app-dev: # Сервис разработки user-service
    container_name: app-dev
    build:
      context: ../services/user-service
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - ../services/user-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users-service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=321321
      - PRIVAT_KEY=secret_key_safasf
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=user-service
      - KAFKA_GROUP_ID=user-service
    depends_on: # Зависимость от сервиса db
      - db
      - redis
      - kafka
    command: sh -c "npm install && npx cross-env NODE_ENV=docker nest start --watch" # Команда для запуска приложения в режиме разработки

  product-app-dev: # Сервис разработки product-service
    container_name: product-app-dev
    build:
      context: ../services/product-service
      dockerfile: Dockerfile.dev
    ports:
      - '5001:5001'
      - '50051:50051' # gRPC порт
    volumes:
      - ../services/product-service:/app
      - /app/node_modules
    environment:
      - PORT=5001
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=product-service
    depends_on:
      - product-db
      - redis
      - kafka
    command: sh -c "npm install && npx cross-env NODE_ENV=docker nest start --watch"

  order-app-dev: # Сервис разработки order-service
    container_name: order-app-dev
    build:
      context: ../services/order-service
      dockerfile: Dockerfile.dev
    ports:
      - '5002:5002'
    volumes:
      - ../services/order-service:/app
      - /app/node_modules
    environment:
      - PORT=5002
      - DB_HOST=order-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=order-service
    depends_on:
      - order-db
      - redis
      - kafka
    command: sh -c "npm install && npx cross-env NODE_ENV=docker nest start --watch"

  cart-app-dev: # Сервис разработки order-service
    container_name: cart-app-dev
    build:
      context: ../services/cart-service
      dockerfile: Dockerfile.dev
    ports:
      - '5003:5003'
    volumes:
      - ../services/cart-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker
      - PORT=5003
      - DB_HOST=cart-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cart-service
      - PRODUCT_SERVICE_GRPC_URL=product-app-dev:50051
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=cart-service
      - KAFKA_GROUP_ID=cart-service
    depends_on:
      - cart-db
      - redis
      - kafka
      - product-app-dev # Важно: зависимость от Product Service
    command: sh -c "npm install && npx cross-env NODE_ENV=docker nest start --watch"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - '2181:2181'
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      # 9092 - для контейнеров внутри docker network (kafka:9092)
      # 9094 - для приложений, запущенных на хост-машине (localhost:9094)
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      # Два listener'а:
      # - PLAINTEXT слушает внутри docker network
      # - PLAINTEXT_HOST нужен для подключений с твоего ПК
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    restart: always

  redis-insight: # не работает через браузер
    image: redis/redisinsight:latest
    ports:
      - '8002:8001'
    volumes:
      - redis-insight-data:/db
    restart: always
    depends_on:
      - redis

  db: # Сервис базы данных для user-service
    container_name: db_user
    image: postgres:14-alpine # Используем образ Postgres
    ports:
      - '5433:5432' # Порт для доступа к базе данных
    environment: # Переменные окружения
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users-service
    volumes:
      - postgres_data:/var/lib/postgresql/data # Волюм для хранения данных базы данных при остановке контейнера
    restart: always

  product-db: # Сервис базы данных для product-service
    container_name: db_product
    image: postgres:14-alpine
    ports:
      - '5434:5432' # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-service
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    restart: always

  order-db: # Сервис базы данных для order-service
    container_name: db_order
    image: postgres:14-alpine
    ports:
      - '5435:5432' # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order-service
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    restart: always
  cart-db: # Сервис базы данных для cart-service
    container_name: db_cart
    image: postgres:14-alpine
    ports:
      - '5436:5432' # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cart-service
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin: # Сервис pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment: # Переменные окружения
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on: # Зависимость от сервиса db
      - db
    restart: always # Перезапуск сервиса при изменении

volumes: # Волюмы для хранения данных баз данных
  postgres_data: # сохраняет данные Postgres для user-service
  product_postgres_data: # сохраняет данные Postgres для product-service
  order_postgres_data: # сохраняет данные Postgres для order-service
  cart_postgres_data: # сохраняет данные Postgres для cart-service
  redis-data: # сохраняет данные Redis
  redis-insight-data: # сохраняет данные RedisInsight

