services:
  app-dev: # Сервис разработки user-service
    build:
      context: ../services/user-service
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ../services/user-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users-service
    depends_on: # Зависимость от сервиса db
      - db
      - redis
    command: yarn start:dev # Команда для запуска приложения в режиме разработки

  product-app-dev: # Сервис разработки product-service
    build:
      context: ../services/product-service
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ../services/product-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker # чтобы Nest читал .docker.env
    depends_on:
      - product-db
      - redis
    command: yarn start:dev

  order-app-dev: # Сервис разработки order-service
    build:
      context: ../services/order-service
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    volumes:
      - ../services/order-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker # чтобы Nest читал .docker.env
    depends_on:
      - order-db
      - redis
    command: yarn start:dev

  cart-app-dev: # Сервис разработки order-service
    build:
      context: ../services/cart-service
      dockerfile: Dockerfile.dev
    ports:
      - "5003:5003"
    volumes:
      - ../services/cart-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=docker # чтобы Nest читал .docker.env
    depends_on:
      - cart-db
      - redis
    command: yarn start:dev

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: always

  redis-insight: # не работает через браузер
    image: redis/redisinsight:latest
    ports:
      - "8002:8001"
    volumes:
      - redis-insight-data:/db
    restart: always
    depends_on:
      - redis

  db: # Сервис базы данных для user-service
    container_name: db_user
    image: postgres:14-alpine # Используем образ Postgres
    ports:
      - "5433:5432" # Порт для доступа к базе данных
    environment: # Переменные окружения
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users-service
    volumes:
      - postgres_data:/var/lib/postgresql/data # Волюм для хранения данных базы данных при остановке контейнера
    restart: always

  product-db: # Сервис базы данных для product-service
    container_name: db_product
    image: postgres:14-alpine
    ports:
      - "5434:5432" # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-service
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    restart: always

  order-db: # Сервис базы данных для order-service
    container_name: db_order
    image: postgres:14-alpine
    ports:
      - "5435:5432" # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order-service
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    restart: always
  cart-db: # Сервис базы данных для cart-service
    container_name: db_cart
    image: postgres:14-alpine
    ports:
      - "5436:5432" # Порт для доступа к базе данных
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cart-service
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin: # Сервис pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment: # Переменные окружения
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on: # Зависимость от сервиса db
      - db
    restart: always # Перезапуск сервиса при изменении

volumes: # Волюмы для хранения данных баз данных
  postgres_data: # сохраняет данные Postgres для user-service
  product_postgres_data: # сохраняет данные Postgres для product-service
  order_postgres_data: # сохраняет данные Postgres для order-service
  cart_postgres_data: # сохраняет данные Postgres для cart-service
  mongodb_data: # сохраняет данные MongoDB
  redis-data: # сохраняет данные Redis
  redis-insight-data: # сохраняет данные RedisInsight
